"""Initial schema with 6 core modules

Revision ID: 1be60f7aface
Revises: 
Create Date: 2026-04-21 13:44:31.892883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be60f7aface'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=150), nullable=False),
    sa.Column('f_trade_name', sa.String(length=150), nullable=True),
    sa.Column('f_document', sa.String(length=30), nullable=True),
    sa.Column('f_phone', sa.String(length=50), nullable=True),
    sa.Column('f_email', sa.String(length=150), nullable=True),
    sa.Column('f_address', sa.Text(), nullable=True),
    sa.Column('f_city', sa.String(length=100), nullable=True),
    sa.Column('f_state', sa.String(length=100), nullable=True),
    sa.Column('f_country', sa.String(length=100), nullable=True),
    sa.Column('f_notes', sa.Text(), nullable=True),
    sa.Column('f_is_active', sa.CHAR(length=1), nullable=True),
    sa.Column('f_created_at', sa.DateTime(), nullable=True),
    sa.Column('f_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_hotel_id'), 't_hotel', ['id'], unique=False)
    op.create_table('t_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=100), nullable=False),
    sa.Column('f_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_role_f_name'), 't_role', ['f_name'], unique=True)
    op.create_index(op.f('ix_t_role_id'), 't_role', ['id'], unique=False)
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_username', sa.String(length=100), nullable=False),
    sa.Column('f_password_hash', sa.Text(), nullable=False),
    sa.Column('f_email', sa.String(length=150), nullable=True),
    sa.Column('f_is_active', sa.CHAR(length=1), nullable=True),
    sa.Column('f_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_user_f_username'), 't_user', ['f_username'], unique=True)
    op.create_index(op.f('ix_t_user_id'), 't_user', ['id'], unique=False)
    op.create_table('t_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_user_id', sa.Integer(), nullable=True),
    sa.Column('f_entity_name', sa.String(length=100), nullable=True),
    sa.Column('f_entity_id', sa.Integer(), nullable=True),
    sa.Column('f_action', sa.String(length=50), nullable=True),
    sa.Column('f_old_value', sa.Text(), nullable=True),
    sa.Column('f_new_value', sa.Text(), nullable=True),
    sa.Column('f_created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['f_user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_audit_log_id'), 't_audit_log', ['id'], unique=False)
    op.create_table('t_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_hotel_id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=150), nullable=False),
    sa.Column('f_event_type', sa.String(length=50), nullable=True),
    sa.Column('f_start_date', sa.Date(), nullable=False),
    sa.Column('f_end_date', sa.Date(), nullable=False),
    sa.Column('f_expected_guests', sa.Integer(), nullable=True),
    sa.Column('f_expected_families', sa.Integer(), nullable=True),
    sa.Column('f_status', sa.String(length=30), nullable=True),
    sa.Column('f_notes', sa.Text(), nullable=True),
    sa.Column('f_created_at', sa.DateTime(), nullable=True),
    sa.Column('f_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['f_hotel_id'], ['t_hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_event_id'), 't_event', ['id'], unique=False)
    op.create_table('t_hotel_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_hotel_id', sa.Integer(), nullable=False),
    sa.Column('f_room_number', sa.String(length=20), nullable=False),
    sa.Column('f_room_type', sa.String(length=50), nullable=True),
    sa.Column('f_floor', sa.String(length=50), nullable=True),
    sa.Column('f_block', sa.String(length=50), nullable=True),
    sa.Column('f_capacity', sa.Integer(), nullable=False),
    sa.Column('f_status', sa.String(length=30), nullable=True),
    sa.Column('f_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['f_hotel_id'], ['t_hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_hotel_room_id'), 't_hotel_room', ['id'], unique=False)
    op.create_table('t_hotel_space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_hotel_id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=150), nullable=False),
    sa.Column('f_space_type', sa.String(length=50), nullable=False),
    sa.Column('f_capacity', sa.Integer(), nullable=True),
    sa.Column('f_floor', sa.String(length=50), nullable=True),
    sa.Column('f_block', sa.String(length=50), nullable=True),
    sa.Column('f_is_active', sa.CHAR(length=1), nullable=True),
    sa.Column('f_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['f_hotel_id'], ['t_hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_hotel_space_id'), 't_hotel_space', ['id'], unique=False)
    op.create_table('t_user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_user_id', sa.Integer(), nullable=False),
    sa.Column('f_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['f_role_id'], ['t_role.id'], ),
    sa.ForeignKeyConstraint(['f_user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_user_role_id'), 't_user_role', ['id'], unique=False)
    op.create_table('t_event_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_event_id', sa.Integer(), nullable=False),
    sa.Column('f_config_key', sa.String(length=100), nullable=False),
    sa.Column('f_config_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['f_event_id'], ['t_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_event_configuration_id'), 't_event_configuration', ['id'], unique=False)
    op.create_table('t_event_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_event_id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=100), nullable=False),
    sa.Column('f_period_type', sa.String(length=50), nullable=True),
    sa.Column('f_start_date', sa.Date(), nullable=False),
    sa.Column('f_end_date', sa.Date(), nullable=False),
    sa.Column('f_sort_order', sa.Integer(), nullable=True),
    sa.Column('f_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['f_event_id'], ['t_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_event_period_id'), 't_event_period', ['id'], unique=False)
    op.create_table('t_event_space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_event_id', sa.Integer(), nullable=False),
    sa.Column('f_space_id', sa.Integer(), nullable=False),
    sa.Column('f_usage_type', sa.String(length=50), nullable=True),
    sa.Column('f_is_active', sa.CHAR(length=1), nullable=True),
    sa.Column('f_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['f_event_id'], ['t_event.id'], ),
    sa.ForeignKeyConstraint(['f_space_id'], ['t_hotel_space.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_event_space_id'), 't_event_space', ['id'], unique=False)
    op.create_table('t_guest_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_event_id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=150), nullable=False),
    sa.Column('f_group_type', sa.String(length=50), nullable=True),
    sa.Column('f_phone', sa.String(length=50), nullable=True),
    sa.Column('f_email', sa.String(length=150), nullable=True),
    sa.Column('f_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['f_event_id'], ['t_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_guest_group_id'), 't_guest_group', ['id'], unique=False)
    op.create_table('t_hotel_kitchen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_hotel_id', sa.Integer(), nullable=False),
    sa.Column('f_space_id', sa.Integer(), nullable=True),
    sa.Column('f_name', sa.String(length=150), nullable=False),
    sa.Column('f_kitchen_type', sa.String(length=50), nullable=True),
    sa.Column('f_capacity_level', sa.String(length=50), nullable=True),
    sa.Column('f_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['f_hotel_id'], ['t_hotel.id'], ),
    sa.ForeignKeyConstraint(['f_space_id'], ['t_hotel_space.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_hotel_kitchen_id'), 't_hotel_kitchen', ['id'], unique=False)
    op.create_table('t_hotel_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_hotel_id', sa.Integer(), nullable=False),
    sa.Column('f_space_id', sa.Integer(), nullable=True),
    sa.Column('f_table_code', sa.String(length=30), nullable=False),
    sa.Column('f_capacity', sa.Integer(), nullable=False),
    sa.Column('f_shape', sa.String(length=30), nullable=True),
    sa.Column('f_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['f_hotel_id'], ['t_hotel.id'], ),
    sa.ForeignKeyConstraint(['f_space_id'], ['t_hotel_space.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_hotel_table_id'), 't_hotel_table', ['id'], unique=False)
    op.create_table('t_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_event_id', sa.Integer(), nullable=False),
    sa.Column('f_title', sa.String(length=200), nullable=False),
    sa.Column('f_description', sa.Text(), nullable=True),
    sa.Column('f_priority', sa.String(length=20), nullable=True),
    sa.Column('f_status', sa.String(length=30), nullable=True),
    sa.Column('f_task_type', sa.String(length=50), nullable=True),
    sa.Column('f_assigned_to_staff_id', sa.Integer(), nullable=True),
    sa.Column('f_due_datetime', sa.DateTime(), nullable=True),
    sa.Column('f_started_at', sa.DateTime(), nullable=True),
    sa.Column('f_completed_at', sa.DateTime(), nullable=True),
    sa.Column('f_created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['f_event_id'], ['t_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_task_id'), 't_task', ['id'], unique=False)
    op.create_table('t_guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_group_id', sa.Integer(), nullable=False),
    sa.Column('f_full_name', sa.String(length=150), nullable=False),
    sa.Column('f_gender', sa.String(length=20), nullable=True),
    sa.Column('f_birth_date', sa.Date(), nullable=True),
    sa.Column('f_document', sa.String(length=50), nullable=True),
    sa.Column('f_phone', sa.String(length=50), nullable=True),
    sa.Column('f_email', sa.String(length=150), nullable=True),
    sa.Column('f_guest_type', sa.String(length=50), nullable=True),
    sa.Column('f_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['f_group_id'], ['t_guest_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_guest_id'), 't_guest', ['id'], unique=False)
    op.create_table('t_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_event_id', sa.Integer(), nullable=False),
    sa.Column('f_group_id', sa.Integer(), nullable=False),
    sa.Column('f_start_date', sa.Date(), nullable=False),
    sa.Column('f_end_date', sa.Date(), nullable=False),
    sa.Column('f_package_type', sa.String(length=50), nullable=True),
    sa.Column('f_status', sa.String(length=30), nullable=True),
    sa.Column('f_total_guests', sa.Integer(), nullable=True),
    sa.Column('f_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['f_event_id'], ['t_event.id'], ),
    sa.ForeignKeyConstraint(['f_group_id'], ['t_guest_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_reservation_id'), 't_reservation', ['id'], unique=False)
    op.create_table('t_task_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_task_id', sa.Integer(), nullable=False),
    sa.Column('f_staff_member_id', sa.Integer(), nullable=True),
    sa.Column('f_comment', sa.Text(), nullable=False),
    sa.Column('f_created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['f_task_id'], ['t_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_task_comment_id'), 't_task_comment', ['id'], unique=False)
    op.create_table('t_task_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_task_id', sa.Integer(), nullable=False),
    sa.Column('f_old_status', sa.String(length=30), nullable=True),
    sa.Column('f_new_status', sa.String(length=30), nullable=True),
    sa.Column('f_changed_by_staff_id', sa.Integer(), nullable=True),
    sa.Column('f_changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['f_task_id'], ['t_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_task_status_history_id'), 't_task_status_history', ['id'], unique=False)
    op.create_table('t_room_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_reservation_id', sa.Integer(), nullable=False),
    sa.Column('f_room_id', sa.Integer(), nullable=False),
    sa.Column('f_start_date', sa.Date(), nullable=False),
    sa.Column('f_end_date', sa.Date(), nullable=False),
    sa.Column('f_checkin_status', sa.String(length=30), nullable=True),
    sa.Column('f_checkout_status', sa.String(length=30), nullable=True),
    sa.Column('f_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['f_reservation_id'], ['t_reservation.id'], ),
    sa.ForeignKeyConstraint(['f_room_id'], ['t_hotel_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_room_allocation_id'), 't_room_allocation', ['id'], unique=False)
    op.create_table('t_special_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_event_id', sa.Integer(), nullable=False),
    sa.Column('f_group_id', sa.Integer(), nullable=True),
    sa.Column('f_guest_id', sa.Integer(), nullable=True),
    sa.Column('f_request_type', sa.String(length=50), nullable=True),
    sa.Column('f_priority', sa.String(length=20), nullable=True),
    sa.Column('f_status', sa.String(length=30), nullable=True),
    sa.Column('f_description', sa.Text(), nullable=False),
    sa.Column('f_notes', sa.Text(), nullable=True),
    sa.Column('f_created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['f_event_id'], ['t_event.id'], ),
    sa.ForeignKeyConstraint(['f_group_id'], ['t_guest_group.id'], ),
    sa.ForeignKeyConstraint(['f_guest_id'], ['t_guest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_special_request_id'), 't_special_request', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_special_request_id'), table_name='t_special_request')
    op.drop_table('t_special_request')
    op.drop_index(op.f('ix_t_room_allocation_id'), table_name='t_room_allocation')
    op.drop_table('t_room_allocation')
    op.drop_index(op.f('ix_t_task_status_history_id'), table_name='t_task_status_history')
    op.drop_table('t_task_status_history')
    op.drop_index(op.f('ix_t_task_comment_id'), table_name='t_task_comment')
    op.drop_table('t_task_comment')
    op.drop_index(op.f('ix_t_reservation_id'), table_name='t_reservation')
    op.drop_table('t_reservation')
    op.drop_index(op.f('ix_t_guest_id'), table_name='t_guest')
    op.drop_table('t_guest')
    op.drop_index(op.f('ix_t_task_id'), table_name='t_task')
    op.drop_table('t_task')
    op.drop_index(op.f('ix_t_hotel_table_id'), table_name='t_hotel_table')
    op.drop_table('t_hotel_table')
    op.drop_index(op.f('ix_t_hotel_kitchen_id'), table_name='t_hotel_kitchen')
    op.drop_table('t_hotel_kitchen')
    op.drop_index(op.f('ix_t_guest_group_id'), table_name='t_guest_group')
    op.drop_table('t_guest_group')
    op.drop_index(op.f('ix_t_event_space_id'), table_name='t_event_space')
    op.drop_table('t_event_space')
    op.drop_index(op.f('ix_t_event_period_id'), table_name='t_event_period')
    op.drop_table('t_event_period')
    op.drop_index(op.f('ix_t_event_configuration_id'), table_name='t_event_configuration')
    op.drop_table('t_event_configuration')
    op.drop_index(op.f('ix_t_user_role_id'), table_name='t_user_role')
    op.drop_table('t_user_role')
    op.drop_index(op.f('ix_t_hotel_space_id'), table_name='t_hotel_space')
    op.drop_table('t_hotel_space')
    op.drop_index(op.f('ix_t_hotel_room_id'), table_name='t_hotel_room')
    op.drop_table('t_hotel_room')
    op.drop_index(op.f('ix_t_event_id'), table_name='t_event')
    op.drop_table('t_event')
    op.drop_index(op.f('ix_t_audit_log_id'), table_name='t_audit_log')
    op.drop_table('t_audit_log')
    op.drop_index(op.f('ix_t_user_id'), table_name='t_user')
    op.drop_index(op.f('ix_t_user_f_username'), table_name='t_user')
    op.drop_table('t_user')
    op.drop_index(op.f('ix_t_role_id'), table_name='t_role')
    op.drop_index(op.f('ix_t_role_f_name'), table_name='t_role')
    op.drop_table('t_role')
    op.drop_index(op.f('ix_t_hotel_id'), table_name='t_hotel')
    op.drop_table('t_hotel')
    # ### end Alembic commands ###
